### ISSUE TITLE
ConfigSpace to ParameterSpace loading

### ISSUE THREAD

**Issue by LGro** [boschresearch/parameterspace#36]
Add initialization for `ParameterSpace` instances from `ConfigSpace` JSON representations.

**Comment by dynobo** [comment]
Could you please elaborate, why it is desired to have initialization from the dict rather than from a `ConfigSpace`-Instance? 
I'm asking, because conversion from JSON seems a bit more error prone and it could be difficult to handle in case differences in the dict representation of different ConfigSpace version.

**Comment by LGro** [comment]
Because in my understanding we would then use the types from the `configspace` package for type hints and isinstance checks, which introduces the `configspace` package as a dependency for `parameterspace`, which I'd like to avoid because it requires e.g. `cython`.

**Comment by dynobo** [comment]
>  I'd like to avoid because it requires e.g. cython.

Fair enough... :+1:

**Comment by LGro** [comment]
Currently blocked by #38
